### PR TITLE
fix for when we only have one message type

### PR DESCRIPTION
**Pull request by jarrettchisholm**
I'm not sure why, but it looks like the total number of message types was being subtracted by one. if I remove that subtraction, it seems to fix the issue.

### CODE REVIEW

**Comment by gafferongames** [comment]
While this fixes it, it's not perfectly efficient.

If you have 16 message types, you are serializing a type value in the range [0,15], hence the -1.

The problem occurs when the number of message types is 1, then it subtracts and get zero.

The code as written is attempting to go, oh, there is only one message type, so don't serialize the message type as an integer, since serializing an int in range [0,0] is undefined.

Most likely, there is a bug in the code such that there is uninitialized data on read in one of the serialize functions, such that the message type is not defaulted to 0. This is my guess anyway.

Could you try fixing this in such a way that it remains efficient? eg. keeps the -1, but special cases the numMessageTypes = 1 case.

Thanks!

**Comment by jarrettchisholm** [comment]
Okay cool.

I gave it a shot, let me know what you think.

**Comment by gafferongames** [comment]
As long as it works when there is only one message type, and passes all unit tests (which it just did), I'm down. Thanks!

**Comment by gafferongames** [comment]
Yes, the issue only manifested on certain compilers and systems. It's not surprising that you cannot repro it. I was never able to either.

**Comment by FredGithub** [comment]
Okay. @jarrettchisholm can you explain the intention behind the changes you made? Also, do you happen to have another OS you could test this issue on?

What is the issue exactly? Lost messages? Crash?

**Comment by jarrettchisholm** [comment]
Sorry, it looks like I forgot to add the issue to this pull request. The issue is here: https://github.com/networkprotocol/yojimbo/issues/77

The operating system and compiler versions are in the issue, as is a zip file that contains a slightly modified version of server.cpp, client.cpp, and shared.h in order to reproduce.

Pre-patch, if you compile with debug and a single message type, the client and server demo will always fail regardless of compiler or OS, as the assertion fails for `yojimbo_assert( min < max );`. The error looks something like this:
```
connecting client (insecure)
client id is 0ba0ab020a06d7e5
client started on port 60718
client connecting to server 127.0.0.1:40000 [1/1]
client address is 0.0.0.0:60718
assert failed: ( 0 < maxMessageType ), function yojimbo::SerializeBlockFragment, file c:\users\jarrett\projects\yojimbo\yojimbo.cpp, line 1450
```

I've tested this on both Windows and Linux with the same result.

If I compile in release mode with a single message type, I get an error like the following in Linux:

```
started server on port 40000 (insecure)
server listening on 127.0.0.1:40000
server started with 64 client slots
server address is 127.0.0.1:40000
server accepted client 127.0.0.1:51351 1c8ff1a502bb1dbd in slot 0
error: failed to serialize channel 0
error: serialize connection packet failed (read packet)
error: failed to read packet
Segmentation fault (core dumped)
```

I am using GCC 6.4.0.

I suspect the problem comes from using the function `__builtin_clz`. This function is only used if GCC is the compiler, and the result of the function is undefined if the input value is 0, which it is when you only have one message type (ref: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html).

> And  more importantly, can we revert the pull request? The changes make the  behavior wrong IMO, since you're not supposed to make a 0 bits write,  and even then, the code is now inconsistent (other asserts later down  the line still check that bits is > 0)

The pull request makes the behavior in GCC the same as other compilers, which was already to do a zero bit write. I'm not sure whether a zero bit write is the correct way to do this, but that was already behaviour that was here.

As far as those asserts go, if I remove the `yojimbo_assert( min < max );` asserts, the `yojimbo_assert( bits > 0 );` asserts are never called in a debug build. I'm not a 100% sure where, but I'm guessing there's some logic to simply not write if there are zero bits to be written. So ultimately, I don't think a zero bit write actually happens.

**Comment by jarrettchisholm** [comment]
Sorry, it looks like I forgot to add the issue to this pull request. The issue is here: https://github.com/networkprotocol/yojimbo/issues/77

The operating system and compiler versions are in the issue, as is a zip file that contains a slightly modified version of server.cpp, client.cpp, and shared.h in order to reproduce.

Pre-patch, if you compile with debug and a single message type, the client and server demo will always fail regardless of compiler or OS, as the assertion fails for `yojimbo_assert( min < max );`. The error looks something like this:
```
connecting client (insecure)
client id is 0ba0ab020a06d7e5
client started on port 60718
client connecting to server 127.0.0.1:40000 [1/1]
client address is 0.0.0.0:60718
assert failed: ( 0 < maxMessageType ), function yojimbo::SerializeBlockFragment, file c:\users\jarrett\projects\yojimbo\yojimbo.cpp, line 1450
```

I've tested this on both Windows and Linux with the same result.

If I compile in release mode with a single message type, I get an error like the following in Linux:

```
started server on port 40000 (insecure)
server listening on 127.0.0.1:40000
server started with 64 client slots
server address is 127.0.0.1:40000
server accepted client 127.0.0.1:51351 1c8ff1a502bb1dbd in slot 0
error: failed to serialize channel 0
error: serialize connection packet failed (read packet)
error: failed to read packet
Segmentation fault (core dumped)
```

I am using GCC 6.4.0.

I suspect the problem comes from using the function `__builtin_clz`. This function is only used if GCC is the compiler, and the result of the function is undefined if the input value is 0, which it is when you only have one message type (ref: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html).

> And  more importantly, can we revert the pull request? The changes make the  behavior wrong IMO, since you're not supposed to make a 0 bits write,  and even then, the code is now inconsistent (other asserts later down  the line still check that bits is > 0)

The pull request makes the behavior in GCC the same as other compilers, which was already to do a zero bit write. I'm not sure whether a zero bit write is the correct way to do this, but that was already behaviour that was here.

As far as those asserts go, if I remove the `yojimbo_assert( min < max );` asserts, the `yojimbo_assert( bits > 0 );` asserts are never called in a debug build. I'm not a 100% sure where, but I'm guessing there's some logic to simply not write if there are zero bits to be written. So ultimately, I don't think a zero bit write actually happens.

**Comment by jarrettchisholm** [comment]
Sorry, it looks like I forgot to add the issue to this pull request. The issue is here: https://github.com/networkprotocol/yojimbo/issues/77

The operating system and compiler versions are in the issue, as is a zip file that contains a slightly modified version of server.cpp, client.cpp, and shared.h in order to reproduce.

Pre-patch, if you compile with debug and a single message type, the client and server demo will always fail regardless of compiler or OS, as the assertion fails for `yojimbo_assert( min < max );`. The error looks something like this:
```
connecting client (insecure)
client id is 0ba0ab020a06d7e5
client started on port 60718
client connecting to server 127.0.0.1:40000 [1/1]
client address is 0.0.0.0:60718
assert failed: ( 0 < maxMessageType ), function yojimbo::SerializeBlockFragment, file c:\users\jarrett\projects\yojimbo\yojimbo.cpp, line 1450
```

I've tested this on both Windows and Linux with the same result.

If I compile in release mode with a single message type, I get an error like the following in Linux:

```
started server on port 40000 (insecure)
server listening on 127.0.0.1:40000
server started with 64 client slots
server address is 127.0.0.1:40000
server accepted client 127.0.0.1:51351 1c8ff1a502bb1dbd in slot 0
error: failed to serialize channel 0
error: serialize connection packet failed (read packet)
error: failed to read packet
Segmentation fault (core dumped)
```

I am using GCC 6.4.0.

I suspect the problem comes from using the function `__builtin_clz`. This function is only used if GCC is the compiler, and the result of the function is undefined if the input value is 0, which it is when you only have one message type (ref: https://gcc.gnu.org/onlinedocs/gcc/Other-Builtins.html).

> And  more importantly, can we revert the pull request? The changes make the  behavior wrong IMO, since you're not supposed to make a 0 bits write,  and even then, the code is now inconsistent (other asserts later down  the line still check that bits is > 0)

The pull request makes the behavior in GCC the same as other compilers, which was already to do a zero bit write. I'm not sure whether a zero bit write is the correct way to do this, but that was already behaviour that was here.

As far as those asserts go, if I remove the `yojimbo_assert( min < max );` asserts, the `yojimbo_assert( bits > 0 );` asserts are never called in a debug build. I'm not a 100% sure where, but I'm guessing there's some logic to simply not write if there are zero bits to be written. So ultimately, I don't think a zero bit write actually happens.

**Comment by FredGithub** [comment]
Thanks for the details! Okay, it seems it only happens for block messages, and I think I know why. As we know, normal messages serialization don't write the message type at all if there is only one message type:

```
if ( maxMessageType > 0 )
{
	serialize_int( stream, messageTypes[i], 0, maxMessageType );
}
else
{
	messageTypes[i] = 0;
}
```

But the block message serialization doesn't do the same check, creating a 0 bits serialization and asserting later down the line:

```
// block message

serialize_int( stream, block.messageType, 0, maxMessageType );
```

So I think a proper fix rather than changing the asserts is to do the same kind of check here. But I would definitely put back the asserts as they were before, since a 0 bits serialization is not a valid use case.

I leave the decision whether to keep `__builtin_clz` or not to @gafferongames. I have no idea if it's more efficient or not. If we put it back, we should catch the special case where `( min == max )` to avoid the undefined behavior of `__builtin_clz`. 

I can try to make a pull request, I'd like to add tests for the message type serialization skipping, so that the bug never comes back :)

**Comment by FredGithub** [comment]
Made a poper fix in #107. @jarrettchisholm if you have a chance to test it in your project, please let me know how it goes!

**Pull request merged**
