### PR TITLE
Upgrade reliable to latest

### PR DESCRIPTION
**Pull request by jorgenpt**
- Fix a memory leak when the sequence buffer wraps
- Fix receiving packets close to `max_packet_size`

### CODE REVIEW

**Comment by gafferongames** [comment]
Do all tests pass in Yojimbo?

**Comment by jorgenpt** [comment]
@gafferongames I'm about to find out as I'm also setting up the CI stuff for yojimbo so we can get pull request test feedback. ;)

**Comment by gafferongames** [comment]
Perfect

**Comment by jorgenpt** [comment]
But yes, the tests pass on this pull request :) (I just realized that even if the GitHub Workflow is merged, it might not run on a pull request that was created before it was merged.)

**Pull request merged**
